### PR TITLE
Bump BR for gcc 8.3 support; point submodule at upstream

### PR DESCRIPTION
**Pull request by davidbiancolin**
See firesim/firesim#290.

### CODE REVIEW

**Comment by NathanTP** [comment]
I fixed the initramfs thing. full_test.sh sort of passes (modulo the issues in #26 which are unrelated to this PR). I didn't test on firesim itself, just disk and initramfs based builds on spike and qemu.

**Comment by davidbiancolin** [comment]
Thanks for bringing this home Nathan.

**Comment by NathanTP** [comment]
This should probably merge against dev instead of master. I haven't really thought it out, but I suppose it makes sense to keep master in sync with firesim master.

**Comment by davidbiancolin** [comment]
You're right, I carelessly opened it up against the wrong base branch.

**Pull request merged**
